### ISSUE TITLE
Intellisense does not work with 3rd party scss that uses "exports" in package.json

### ISSUE THREAD

**Issue by MilesWellsSVT** [wkillerud/some-sass#268]
### In which editor is this a problem?

Visual Studio Code

### Describe the bug

VSCode: 1.95.3
Some Sass: 4.0.2

Assuming I've installed 3rd party styles that include variables that exist on the local filesystem as such:
```scss
// node_modules/styles-package/dist/scss/variables/_fonts.scss
$font-weight-bold: 700;

// node_modules/styles-package/dist/scss/variables/_index.scss
@forward './fonts';
``` 

and that package uses package.json `exports` e.g.

```json
{
    "name": "styles-package",
    "exports": {
        "./scss/variables": "./dist/scss/variables/_index.scss"
    }
}
```

Then I am able to import these variables in a `.scss` file using:
```scss
@use 'styles-package/scss/variables' as vars;

.myClass {
    font-weight: vars.$font-weight-bold;
}
```

I am using Next v14.1.3 and this works with the built-in sass support, but I do not get any intellisense in VSCode.

I _do_ get intellisense by updating the `@use` path to the exact file path instead of the `exports` alias:

```scss
@use 'styles-package/dist/scss/variables' as vars;

.myClass {
    font-weight: vars.$font-weight-; // bringing up intellisense here works as expected (shows $font-weight-bold)
}
```

However the sass no longer compiles since there's no `exports` entry to support that `@use` path so it fails to resolve.

### What's the expected result?

I expect to get intellisense.

### Participation

- [x] I am willing to submit a pull request for this issue.

I have marked that I'm willing to submit a PR, but I've never done extension development before so I'd need a pointer on where to start for this issue.
